### ISSUE TITLE
Breaks on saves

### ISSUE THREAD

**Issue by stephhider** [kblease/ProductionQueue#22]
Love this mod but had to stop using it because when I open up a saved file it no longer works and it blocks me from placing down districts.

**Comment by kblease** [comment]
Sorry to hear that, but this sounds like a case of another mod overwriting the necessary files for Production Queue. Do you perhaps use other mods? The one most people have a problem with is Divine Yuri's Custom City Panel, but it could be any mod out there. If you do not use mods please provide me with your save file and I can figure out what is causing your issue.

**Comment by kblease** [comment]
In the event you do use Divine Yuri's Custom City Panel, the easiest thing is to comment out or remove the four lines referencing the two ProductionPanel files from the .modinfo file for that mod. The ProductionPanel.xml file is actually identical to the base game version, and the ProductionPanel.lua only makes a single change which has no meaningful effect on the game. I personally use Divine Yuri's mod this way and can't play without it since it's such an improvement. Looking forward to hearing back from you. I'll leave this issue open for now until we can make sure it's resolved.

**Comment by stephhider** [comment]
Thank you so much I think that worked. I had to start the queue over again but it seems to be working. Appreciate that =)

**Comment by kblease** [comment]
No problem! I'm glad it wasn't a more complicated problem! Thanks for caring enough to bring it to my attention 😄
